// utils/flutterRepair.js

export const KNOWN_ERRORS = [
  {
    pattern: /The getter '(\w+)' isn't defined/,
    category: 'undefined_getter',
    fix: (match) => ({
      title: `Undefined getter: ${match[1]}`,
      suggestion: `Check that '${match[1]}' is defined in your AppState or passed as a prop.`,
      autoFixable: false,
    }),
  },
  {
    pattern: /A value of type '(\w+)' can't be assigned to a variable of type '(\w+)'/,
    category: 'type_mismatch',
    fix: (match) => ({
      title: `Type mismatch: ${match[1]} → ${match[2]}`,
      suggestion: `Use ${match[2] === 'double' ? 'toDouble()' : match[2] === 'String' ? 'toString()' : 'a cast'} to convert.`,
      autoFixable: true,
    }),
  },
  {
    pattern: /Undefined class '(\w+)'/,
    category: 'missing_import',
    fix: (match) => ({
      title: `Missing class: ${match[1]}`,
      suggestion: `Add the correct import for '${match[1]}' to pubspec.yaml.`,
      autoFixable: false,
    }),
  },
  {
    pattern: /RenderFlex overflowed by ([\d.]+) pixels/,
    category: 'overflow',
    fix: (match) => ({
      title: `Layout overflow by ${match[1]}px`,
      suggestion: 'Wrap the overflowing widget in Expanded(), Flexible(), or SingleChildScrollView().',
      autoFixable: true,
      schemaPatch: { wrap: 'Expanded' },
    }),
  },
  {
    pattern: /Could not find a generator for route named '\/(\w+)'/,
    category: 'missing_route',
    fix: (match) => ({
      title: `Missing route: /${match[1]}`,
      suggestion: `No page with ID '${match[1]}' exists. Add it in the Pages panel.`,
      autoFixable: false,
    }),
  },
  {
    pattern: /GRADLE_BUILD_FAILED|Execution failed for task ':app:merge/,
    category: 'gradle_failure',
    fix: () => ({
      title: 'Gradle build failed',
      suggestion: 'Clean the build: run `flutter clean && flutter pub get`. Check compileSdkVersion in android/app/build.gradle.',
      autoFixable: false,
    }),
  },
  {
    pattern: /uses-sdk:minSdkVersion (\d+) cannot be smaller than version (\d+)/,
    category: 'min_sdk',
    fix: (match) => ({
      title: `minSdkVersion too low: ${match[1]} < ${match[2]}`,
      suggestion: `Set minSdkVersion to ${match[2]} in android/app/build.gradle.`,
      autoFixable: true,
      filePatch: {
        file: 'android/app/build.gradle',
        find: `minSdkVersion ${match[1]}`,
        replace: `minSdkVersion ${match[2]}`,
      },
    }),
  },
  {
    pattern: /Null check operator used on a null value/,
    category: 'null_check',
    fix: () => ({
      title: 'Null check crash (! operator)',
      suggestion: 'A required value was null at runtime. Use ?. and ?? operators instead of !.',
      autoFixable: false,
    }),
  },
];

export const analyzeLog = (logText) => {
  const results = [];
  for (const rule of KNOWN_ERRORS) {
    const match = logText.match(rule.pattern);
    if (match) {
      results.push({ ...rule.fix(match), category: rule.category });
    }
  }
  return results;
};

export const generatePubspec = (schema) => {
  const usesMap = schemaUsesWidget(schema, 'MapView');
  const usesWebView = schemaUsesWidget(schema, 'WebView');
  const usesVideo = schemaUsesWidget(schema, 'VideoPlayer');
  const isFirebase = schema.backendProvider === 'firebase';
  const hasSupabase = schema.supabaseConfig?.url?.length > 5;

  const deps = {
    flutter: '{ sdk: flutter }',
    http: '^1.2.0',
    provider: '^6.1.2',
    flutter_dotenv: '^5.1.0',
  };

  if (isFirebase) {
    deps['firebase_core'] = '^2.27.0';
    deps['firebase_auth'] = '^4.17.0';
    deps['cloud_firestore'] = '^4.15.0';
  } else if (hasSupabase) {
    deps['supabase_flutter'] = '^2.3.4';
  }
  if (usesMap) deps['google_maps_flutter'] = '^2.6.1';
  if (usesWebView) deps['webview_flutter'] = '^4.7.0';
  if (usesVideo) deps['video_player'] = '^2.8.3';

  return `name: appforge_project
description: Generated by AppForge
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
${Object.entries(deps).map(([k, v]) => `  ${k}: ${v}`).join('\n')}

flutter:
  uses-material-design: true
  assets:
    - .env
`;
};