// =============================================================================
// flutterPromptCompiler.js — v2.0 (AppForge AI Architect Edition)
//
// UPGRADE LOG:
//   v2.0 — Dynamic Theme Engine, responsive layout rules,
//           Backend Architect context, Self-Healing repair context,
//           RAG memory-bank retrieval injection.
// =============================================================================

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 1: STRUCTURAL LAYOUT RULES (new in v2.0)
// These rules are ALWAYS injected into every prompt.
// They prevent the top-5 Flutter layout bugs generated by AI models.
// ─────────────────────────────────────────────────────────────────────────────

const STRUCTURAL_LAYOUT_RULES = `
═══════════════════════════════════════════════════════════
MANDATORY LAYOUT RULES — NEVER VIOLATE THESE
═══════════════════════════════════════════════════════════

RULE L-1: PADDING BASELINE
  Every top-level screen must have at minimum 16px horizontal
  padding on all body content. Use:
    padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 24.0)

RULE L-2: COLUMN HEIGHT CONSTRAINT
  A Column inside a ListView or another Column MUST use one of:
    (a) shrinkWrap: true on the ListView
    (b) Expanded() wrapping the inner Column
    (c) SizedBox(height: X, child: Column(...))
  NEVER leave a Column inside a scrollable with unbounded height.

RULE L-3: TEXT IN ROW
  Any Text widget inside a Row MUST be wrapped in Expanded() unless
  it has a fixed width constraint. Otherwise it overflows.
    ✓ Row(children: [Expanded(child: Text('...')), Icon(...)])
    ✗ Row(children: [Text('...'), Icon(...)])

RULE L-4: IMAGE DIMENSIONS
  Every Image.network() MUST have explicit width AND height.
  If the image should fill its parent, use:
    width: double.infinity, height: 200.0, fit: BoxFit.cover

RULE L-5: RESPONSIVE WIDTHS
  Never use hardcoded widths > 320px for full-width elements.
  Use double.infinity or MediaQuery.of(context).size.width instead.
  For cards: width: double.infinity (not width: 375.0)

RULE L-6: SAFE AREA
  Every Scaffold body MUST be wrapped in SafeArea() to avoid
  overlapping with notch/status bar on iOS and Android.

RULE L-7: CONST CONSTRUCTORS
  All widgets with no dynamic data MUST use const constructor:
    const SizedBox(height: 16)
    const EdgeInsets.all(16)
    const Text('Static label')
  This dramatically improves rebuild performance.

RULE L-8: ASYNC CONTEXT SAFETY
  After every await statement that leads to Navigator/Scaffold usage:
    await someAsyncOperation();
    if (!mounted) return;  // ← MANDATORY
    Navigator.pushNamed(context, '/route');

RULE L-9: NULL GUARDS
  Never use ! on data fetched from APIs or Supabase.
  Always use ?. and ?? fallbacks:
    ✓ user?.email ?? 'No email'
    ✗ user!.email
═══════════════════════════════════════════════════════════
`;

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 2: DYNAMIC THEME ENGINE (new in v2.0)
// Converts any AppForge schema theme into full Flutter ThemeData + design tokens.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * hexToArgb — converts #RRGGBB to Flutter's 0xFFRRGGBB notation.
 * Handles both shorthand (#FFF) and full (#FFFFFF) hex codes.
 */
const hexToArgb = (hex) => {
  if (!hex) return '0xFF050609';
  const clean = hex.replace('#', '').trim();
  if (clean.length === 3) {
    const r = clean[0] + clean[0];
    const g = clean[1] + clean[1];
    const b = clean[2] + clean[2];
    return `0xFF${r}${g}${b}`.toUpperCase();
  }
  return `0xFF${clean.slice(0, 6)}`.toUpperCase();
};

/**
 * detectThemeMode — inspects the background color luminance to determine
 * whether the schema is using a dark or light theme.
 */
const detectThemeMode = (bgHex) => {
  if (!bgHex) return 'dark';
  const clean = bgHex.replace('#', '');
  const r = parseInt(clean.slice(0, 2), 16) || 0;
  const g = parseInt(clean.slice(2, 4), 16) || 0;
  const b = parseInt(clean.slice(4, 6), 16) || 0;
  // Relative luminance
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.5 ? 'light' : 'dark';
};

/**
 * buildDynamicThemeBlock — generates a complete, schema-driven theme context
 * block for injection into the AI system prompt.
 */
const buildDynamicThemeBlock = (schema) => {
  const t = schema.theme || {};
  const mode = detectThemeMode(t.background);
  const isDark = mode === 'dark';

  // Derive sensible fallbacks from the primary color
  const primary = t.primary || '#3B82F6';
  const secondary = t.secondary || '#EC4899';
  const background = t.background || (isDark ? '#050609' : '#FFFFFF');
  const surface = isDark ? '#0D1017' : '#F8FAFC';
  const surfaceAlt = isDark ? '#161B22' : '#F1F5F9';
  const textPrimary = isDark ? '#F8FAFC' : '#0F172A';
  const textMuted = isDark ? '#94A3B8' : '#64748B';
  const textSubtle = isDark ? '#64748B' : '#94A3B8';
  const borderColor = isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.08)';
  const fontFamily = t.fontFamily || 'Inter';
  const radius = parseFloat(t.globalRadius) || 12;

  return `
═══════════════════════════════════════════════════════════
DYNAMIC THEME ENGINE — USE EXACTLY THESE TOKENS
Mode: ${mode.toUpperCase()} THEME
═══════════════════════════════════════════════════════════

Dart Color constants (copy-paste ready):
  kPrimary      = const Color(${hexToArgb(primary)})
  kSecondary    = const Color(${hexToArgb(secondary)})
  kBackground   = const Color(${hexToArgb(background)})
  kSurface      = const Color(${hexToArgb(surface)})
  kSurfaceAlt   = const Color(${hexToArgb(surfaceAlt)})
  kTextPrimary  = ${isDark ? 'Colors.white' : 'const Color(0xFF0F172A)'}
  kTextMuted    = const Color(${hexToArgb(textMuted)})
  kTextSubtle   = const Color(${hexToArgb(textSubtle)})
  kBorder       = ${isDark ? 'Colors.white.withOpacity(0.08)' : 'Colors.black.withOpacity(0.08)'}
  kSuccess      = const Color(0xFF22C55E)
  kWarning      = const Color(0xFFF59E0B)
  kError        = const Color(0xFFEF4444)
  kRadius       = ${radius}.0

ThemeData block (inject into MaterialApp):
\`\`\`dart
ThemeData(
  brightness: Brightness.${mode},
  scaffoldBackgroundColor: const Color(${hexToArgb(background)}),
  primaryColor: const Color(${hexToArgb(primary)}),
  colorScheme: ColorScheme.${mode}(
    primary: const Color(${hexToArgb(primary)}),
    secondary: const Color(${hexToArgb(secondary)}),
    background: const Color(${hexToArgb(background)}),
    surface: const Color(${hexToArgb(surface)}),
    onPrimary: Colors.white,
    onBackground: ${isDark ? 'Colors.white' : 'const Color(0xFF0F172A)'},
    onSurface: ${isDark ? 'Colors.white' : 'const Color(0xFF0F172A)'},
  ),
  fontFamily: '${fontFamily}',
  textTheme: const TextTheme(
    headlineLarge: TextStyle(fontWeight: FontWeight.w800, letterSpacing: -0.5),
    headlineMedium: TextStyle(fontWeight: FontWeight.w700),
    bodyLarge: TextStyle(fontSize: 16.0, height: 1.6),
    bodyMedium: TextStyle(fontSize: 14.0, height: 1.5),
    labelSmall: TextStyle(fontSize: 11.0, letterSpacing: 0.8, fontWeight: FontWeight.w600),
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: const Color(${hexToArgb(primary)}),
      foregroundColor: Colors.white,
      padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(${radius}.0),
      ),
      elevation: 0,
      textStyle: const TextStyle(fontWeight: FontWeight.w700, fontSize: 15.0),
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: const Color(${hexToArgb(surfaceAlt)}),
    hintStyle: TextStyle(color: const Color(${hexToArgb(textSubtle)})),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(${radius}.0),
      borderSide: BorderSide.none,
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(${radius}.0),
      borderSide: BorderSide(color: const Color(${hexToArgb(primary)}), width: 1.5),
    ),
    contentPadding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
  ),
)
\`\`\`
═══════════════════════════════════════════════════════════
`;
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 3: WIDGET KNOWLEDGE BASE (unchanged from v1, trimmed for brevity)
// ─────────────────────────────────────────────────────────────────────────────

const WIDGET_KNOWLEDGE = {
  Column: {
    category: 'layout',
    dartClass: 'Column',
    description: 'Vertical flex. RULE: wrap inner Column with Expanded() when inside ListView.',
    dartPattern: `Column(
  mainAxisAlignment: MainAxisAlignment.start,
  crossAxisAlignment: CrossAxisAlignment.stretch,
  children: <Widget>[],
)`,
  },
  Row: {
    category: 'layout',
    dartClass: 'Row',
    description: 'Horizontal flex. RULE: always wrap Text children with Expanded().',
    dartPattern: `Row(
  mainAxisAlignment: MainAxisAlignment.spaceBetween,
  crossAxisAlignment: CrossAxisAlignment.center,
  children: <Widget>[
    Expanded(child: Text('Label')),
    Icon(Icons.chevron_right),
  ],
)`,
  },
  Container: {
    category: 'layout',
    dartClass: 'Container',
    description: 'Decorated box. Use BoxDecoration for shadows, gradients, borders.',
    dartPattern: `Container(
  width: double.infinity,
  padding: const EdgeInsets.all(16.0),
  decoration: BoxDecoration(
    color: kSurface,
    borderRadius: BorderRadius.circular(kRadius),
    boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.1), blurRadius: 16)],
  ),
  child: /* widget */,
)`,
  },
  ListView: {
    category: 'layout',
    dartClass: 'ListView.builder',
    description: 'Scrollable list. Use shrinkWrap:true when nested inside Column.',
    dartPattern: `ListView.builder(
  shrinkWrap: true,
  physics: const ClampingScrollPhysics(),
  itemCount: items.length,
  itemBuilder: (context, index) => ItemCard(item: items[index]),
)`,
  },
  Text: {
    category: 'basic',
    dartClass: 'Text',
    description: 'Displays string. State-bind via ListenableBuilder + AppState.',
    dartPattern: `Text('Label', style: TextStyle(color: kTextPrimary, fontSize: 16.0, fontWeight: FontWeight.w600))`,
  },
  Button: {
    category: 'basic',
    dartClass: 'ElevatedButton',
    dartPattern: `ElevatedButton(
  onPressed: () => Navigator.pushNamed(context, '/route'),
  child: const Text('Action'),
)`,
  },
  Image: {
    category: 'media',
    dartClass: 'Image.network',
    description: 'RULE: always provide width, height, and fit.',
    dartPattern: `Image.network(url, width: double.infinity, height: 200.0, fit: BoxFit.cover,
  errorBuilder: (_, __, ___) => Container(height: 200, color: kSurfaceAlt,
    child: const Icon(Icons.broken_image_rounded, color: Colors.grey)))`,
  },
  Icon: {
    category: 'basic',
    dartClass: 'Icon',
    description: 'Material icon. Lucide names auto-map to Icons.snake_case_rounded.',
    dartPattern: `Icon(Icons.favorite_rounded, color: kPrimary, size: 24.0)`,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 4: BACKEND KNOWLEDGE BASE (unchanged from v1)
// ─────────────────────────────────────────────────────────────────────────────

const BACKEND_KNOWLEDGE = {
  supabase: {
    auth: {
      signIn: `await Supabase.instance.client.auth.signInWithPassword(email: email, password: password);`,
      signUp: `await Supabase.instance.client.auth.signUp(email: email, password: password);`,
      signOut: `await Supabase.instance.client.auth.signOut();`,
      currentUser: `Supabase.instance.client.auth.currentUser`,
    },
    database: {
      select: `final data = await Supabase.instance.client.from('table').select().order('created_at', ascending: false);`,
      insert: `await Supabase.instance.client.from('table').insert({'col': value, 'user_id': userId});`,
      update: `await Supabase.instance.client.from('table').update({'col': newVal}).eq('id', rowId);`,
      delete: `await Supabase.instance.client.from('table').delete().eq('id', rowId);`,
      upsert: `await Supabase.instance.client.from('table').upsert({'id': userId, 'col': val});`,
    },
    errorHandling: `try {
  final data = await Supabase.instance.client.from('table').select().single();
} on PostgrestException catch (e) {
  ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.message)));
} catch (e) {
  debugPrint('Error: $e');
}`,
  },
  firebase: {
    auth: {
      signIn: `await FirebaseAuth.instance.signInWithEmailAndPassword(email: email, password: password);`,
      signUp: `await FirebaseAuth.instance.createUserWithEmailAndPassword(email: email, password: password);`,
    },
    firestore: {
      select: `final snap = await FirebaseFirestore.instance.collection('col').get();`,
      insert: `await FirebaseFirestore.instance.collection('col').add({'field': value, 'createdAt': FieldValue.serverTimestamp()});`,
    },
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 5: SCHEMA SCANNER (unchanged from v1)
// ─────────────────────────────────────────────────────────────────────────────

const scanSchema = (schema) => {
  const widgetTypes = new Set();
  const boundVars = new Set();
  const actionTypes = new Set();
  const navTargets = new Set();
  const apiEndpoints = [];
  const stateVarMap = {};

  const walk = (node) => {
    if (!node) return;
    widgetTypes.add(node.type);
    const p = node.props || {};
    if (p.isBound && p.boundVariable) boundVars.add(p.boundVariable);
    if (p.actionType && p.actionType !== 'none') actionTypes.add(p.actionType);
    if (p.actionChain) {
      p.actionChain.forEach((a) => {
        actionTypes.add(a.type);
        if (a.target) navTargets.add(a.target);
        if (a.url) apiEndpoints.push({ url: a.url, method: a.method || 'GET' });
      });
    }
    (node.children || []).forEach(walk);
  };

  (schema.pages || []).forEach((p) => walk(p.root));
  (schema.appState || []).forEach((s) => {
    stateVarMap[s.key] = { type: s.type, defaultValue: s.value };
  });

  return {
    widgetTypes: [...widgetTypes],
    boundVars: [...boundVars],
    actionTypes: [...actionTypes],
    navTargets: [...navTargets],
    apiEndpoints,
    stateVarMap,
    pageCount: schema.pages?.length || 0,
    tableCount: schema.appConfig?.dbTables?.length || 0,
    hasBottomNav: schema.appConfig?.enableBottomNav || false,
    backend: schema.backendProvider || 'supabase',
    hasSupabase: !!(schema.supabaseConfig?.url?.length > 5),
    hasFirebase: schema.backendProvider === 'firebase',
    usesMap: [...widgetTypes].includes('MapView'),
    usesWebView: [...widgetTypes].includes('WebView'),
    usesVideo: [...widgetTypes].includes('VideoPlayer'),
  };
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 6: STORE THEMES (unchanged from v1)
// ─────────────────────────────────────────────────────────────────────────────

const STORE_THEMES = {
  darkTech: { name: 'Dark Tech', background: '#050609', surface: '#0d1017', primary: '#3b82f6', text: '#f8fafc', textMuted: '#94a3b8', fontFamily: 'Inter' },
  ecommerce: { name: 'E-Commerce', background: '#ffffff', surface: '#f9fafb', primary: '#ec4899', text: '#111827', textMuted: '#6b7280', fontFamily: 'Inter' },
  fintech: { name: 'Fintech', background: '#0f172a', surface: '#1e293b', primary: '#10b981', text: '#f8fafc', textMuted: '#94a3b8', fontFamily: 'Inter' },
  healthcare: { name: 'Healthcare', background: '#f8fafc', surface: '#ffffff', primary: '#06b6d4', text: '#0f172a', textMuted: '#64748b', fontFamily: 'Inter' },
  aiSaas: { name: 'AI SaaS', background: '#020617', surface: '#0f172a', primary: '#38bdf8', text: '#f8fafc', textMuted: '#94a3b8', fontFamily: 'Inter' },
};

const matchTheme = (schema) => {
  const bg = schema.theme?.background?.toLowerCase() || '#000000';
  const primary = schema.theme?.primary?.toLowerCase() || '#3b82f6';
  const isWhite = bg === '#ffffff' || bg.startsWith('#f');
  if (primary.includes('ec4899') && isWhite) return STORE_THEMES.ecommerce;
  if (primary.includes('06b6d4') && isWhite) return STORE_THEMES.healthcare;
  if (primary.includes('10b981')) return STORE_THEMES.fintech;
  if (primary.includes('38bdf8')) return STORE_THEMES.aiSaas;
  return STORE_THEMES.darkTech;
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 7: DART RULES (condensed)
// ─────────────────────────────────────────────────────────────────────────────

const DART_RULES = `
DART 3.x NULL-SAFETY RULES (non-negotiable):
  ✓ ?. and ?? always — never ! on API data
  ✓ const everywhere possible
  ✓ try-catch on all async operations
  ✓ if (!mounted) return; after every await before using context
  ✓ Cast API values: data['price'] as double? ?? 0.0
  ✗ Never chain ! operators
  ✗ Never hardcode colors — always use the token constants above
`;

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 8: MAIN COMPILER — compileFlutterContext
// ─────────────────────────────────────────────────────────────────────────────

export const compileFlutterContext = (schema, task, options = {}) => {
  const {
    includeThemes = true,
    includeBackend = true,
    includePatterns = true,
    focusWidgets = null,
    verbosity = 'full',
    // NEW v2.0 options:
    ragContext = null,      // injected memory-bank snippets
    repairMode = false,     // activates repair-specific instructions
    backendWizard = false,  // activates backend setup wizard context
  } = options;

  const scan = scanSchema(schema);
  const matchedTheme = matchTheme(schema);
  const backendType = scan.backend;

  const widgetsToDocument = focusWidgets
    ? focusWidgets
    : scan.widgetTypes.filter((t) => WIDGET_KNOWLEDGE[t]);

  // ── IDENTITY BLOCK ──────────────────────────────────────────────────────
  const identityBlock = `You are AppForge Flutter Intelligence v2.0 — an expert Flutter 3.19 / Dart 3.3 / ${backendType === 'firebase' ? 'Firebase' : 'Supabase'} engineer.
You have FULL knowledge of the AppForge widget system, dynamic theme engine, state management pattern, and backend integration layer.
You output ONLY valid, production-ready Dart code that compiles on the first attempt.
You ALWAYS follow the mandatory layout rules, use the dynamic theme tokens, and apply null-safety throughout.`;

  // ── TASK BLOCK ──────────────────────────────────────────────────────────
  const taskBlock = `
═══════════════════════════════
TASK: ${task}
═══════════════════════════════`;

  // ── APP CONTEXT BLOCK ───────────────────────────────────────────────────
  const appContextBlock = `
APP CONTEXT:
  Name:        ${schema.app?.name || 'AppForge Project'}
  Backend:     ${backendType === 'firebase' ? 'Firebase' : 'Supabase'}
  Screens:     ${schema.pages?.map((p) => `${p.name} (/${p.id})`).join(', ')}
  Widgets:     ${scan.widgetTypes.join(', ')}
  State vars:  ${Object.entries(scan.stateVarMap).map(([k, v]) => `${k}:${v.type}`).join(', ') || 'none'}
  DB tables:   ${schema.appConfig?.dbTables?.map((t) => `${t.name}(${t.columns?.map((c) => `${c.name}:${c.type}`).join(', ')})`).join(', ') || 'none'}
  Bottom nav:  ${scan.hasBottomNav ? 'enabled' : 'disabled'}
  API routes:  ${schema.apiEndpoints?.map((e) => `${e.method} ${e.url}`).join(', ') || 'none'}`;

  // ── DYNAMIC THEME BLOCK (NEW v2.0) ──────────────────────────────────────
  const dynamicThemeBlock = buildDynamicThemeBlock(schema);

  // ── STRUCTURAL RULES (NEW v2.0) ─────────────────────────────────────────
  const structuralRulesBlock = STRUCTURAL_LAYOUT_RULES;

  // ── STATE BLOCK ─────────────────────────────────────────────────────────
  const stateBlock =
    Object.keys(scan.stateVarMap).length > 0
      ? `
APPSTATE SINGLETON — DO NOT REDEFINE, JUST USE:
${Object.entries(scan.stateVarMap)
  .map(([k, v]) => `  AppState.instance.${k}  // ${v.type}, default: ${v.defaultValue}`)
  .join('\n')}
Read:   AppState.instance.someVar
Write:  AppState.instance.updateSomeVar(newValue)
React:  ListenableBuilder(listenable: AppState.instance, builder: (ctx, _) => widget)`
      : '';

  // ── NAVIGATION BLOCK ────────────────────────────────────────────────────
  const navBlock =
    scan.pageCount > 1
      ? `
NAVIGATION (named routes registered):
${schema.pages?.map((p) => `  '/${p.id}' → ${p.name}`).join('\n')}
Push:    Navigator.pushNamed(context, '/page_id');
Replace: Navigator.pushReplacementNamed(context, '/page_id');
Pop:     Navigator.pop(context);`
      : '';

  // ── WIDGET DOCS BLOCK ───────────────────────────────────────────────────
  let widgetDocsBlock = '';
  if (verbosity === 'full' && widgetsToDocument.length > 0) {
    widgetDocsBlock = '\nWIDGET REFERENCE:';
    widgetsToDocument.slice(0, 6).forEach((type) => {
      const w = WIDGET_KNOWLEDGE[type];
      if (!w) return;
      widgetDocsBlock += `\n── ${type} (${w.dartClass}): ${w.description}\n\`\`\`dart\n${w.dartPattern}\n\`\`\``;
    });
  }

  // ── BACKEND BLOCK ───────────────────────────────────────────────────────
  let backendBlock = '';
  if (includeBackend) {
    const backend = BACKEND_KNOWLEDGE[backendType === 'firebase' ? 'firebase' : 'supabase'];
    if (backend) {
      backendBlock = `\nBACKEND (${backendType}):\n`;
      if (backendType !== 'firebase' && scan.hasSupabase) {
        backendBlock += `\`\`\`dart\n${backend.database.select}\n${backend.database.insert}\n${backend.errorHandling}\n\`\`\``;
      } else if (backendType === 'firebase') {
        backendBlock += `\`\`\`dart\n${backend.auth.signIn}\n${backend.firestore.insert}\n\`\`\``;
      }
    }
  }

  // ── BACKEND WIZARD BLOCK (NEW v2.0) ─────────────────────────────────────
  let backendWizardBlock = '';
  if (backendWizard) {
    backendWizardBlock = compileBackendWizardContext(schema);
  }

  // ── RAG MEMORY INJECTION (NEW v2.0) ─────────────────────────────────────
  let ragBlock = '';
  if (ragContext && ragContext.length > 0) {
    ragBlock = `
═══════════════════════════════════════════════════════════
PROVEN PATTERNS FROM MEMORY BANK (high confidence — prefer these)
═══════════════════════════════════════════════════════════
The following patterns were retrieved from AppForge's curated schema library.
They are PRODUCTION-TESTED. Use them as-is or adapt minimally.

${ragContext
  .map(
    (entry, i) => `── Memory ${i + 1}: ${entry.label} (similarity: ${(entry.similarity * 100).toFixed(0)}%) ──
Description: ${entry.description}
\`\`\`json
${JSON.stringify(entry.schema, null, 2).slice(0, 800)}
\`\`\``
  )
  .join('\n\n')}
═══════════════════════════════════════════════════════════`;
  }

  // ── DART RULES BLOCK ────────────────────────────────────────────────────
  const dartRulesBlock = DART_RULES;

  // ── OUTPUT FORMAT ────────────────────────────────────────────────────────
  const outputBlock = `
OUTPUT REQUIREMENTS:
  - ONLY valid Dart/Flutter code — no markdown explanation unless asked
  - ALWAYS use the kPrimary / kSurface / kTextPrimary token constants defined above
  - NEVER hardcode hex colors — reference the token constants
  - ALWAYS apply Layout Rules L-1 through L-9 above
  - ALWAYS use const wherever the data is static
  - ALWAYS wrap async context usage with: if (!mounted) return;`;

  // ── ASSEMBLE ─────────────────────────────────────────────────────────────
  const sections = [
    identityBlock,
    taskBlock,
    appContextBlock,
    dynamicThemeBlock,
    structuralRulesBlock,
    stateBlock,
    navBlock,
    widgetDocsBlock,
    backendBlock,
    backendWizardBlock,
    ragBlock,
    dartRulesBlock,
    outputBlock,
  ]
    .filter(Boolean)
    .join('\n');

  return sections;
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 9: BACKEND WIZARD CONTEXT (NEW v2.0)
// Used by the AI Setup Wizard to guide beginners through database connection.
// ─────────────────────────────────────────────────────────────────────────────

export const compileBackendWizardContext = (schema) => {
  const tables = schema.appConfig?.dbTables || [];
  const backendType = schema.backendProvider || 'supabase';

  const tableSchemas = tables
    .map((t) => {
      const cols = (t.columns || []).map((c) => `${c.name} ${mapType(c.type)}`).join(', ');
      return `Table "${t.name}": id UUID PK, created_at TIMESTAMPTZ, ${cols}`;
    })
    .join('\n');

  return `
═══════════════════════════════════════════════════════════
BACKEND ARCHITECT MODE — STEP-BY-STEP SETUP WIZARD
═══════════════════════════════════════════════════════════

The user is setting up their backend. Guide them through these exact steps:

STEP 1 — GENERATE SQL SCHEMA
  The following tables are defined in their visual schema:
  ${tableSchemas || '(no tables defined — ask the user what data they want to store)'}

  Generate the complete CREATE TABLE SQL with:
    - UUID primary keys using gen_random_uuid()
    - created_at TIMESTAMPTZ DEFAULT NOW()
    - Row Level Security (RLS) enabled on all tables
    - A read policy: FOR SELECT USING (true)
    - A write policy: FOR INSERT TO authenticated WITH CHECK (true)

STEP 2 — EXPLAIN WHERE TO RUN IT
  Tell the user to:
  1. Open their Supabase dashboard → SQL Editor
  2. Paste the generated SQL
  3. Click "Run"
  4. Screenshot the green ✓ success message

STEP 3 — BIND TO VISUAL CANVAS
  After the SQL runs, show them how to bind a ListView widget to the table:
  \`\`\`dart
  // In the ListView's FutureBuilder, use:
  future: Supabase.instance.client
      .from('${tables[0]?.name || 'your_table'}')
      .select()
      .order('created_at', ascending: false),
  \`\`\`

STEP 4 — TEST THE CONNECTION
  Generate a simple FutureBuilder snippet that fetches one row and prints it.
  This lets the user confirm the connection works before building the full UI.

OUTPUT FORMAT FOR WIZARD:
  Return a JSON object:
  {
    "sql": "complete SQL string",
    "explanation": "friendly plain-English explanation of what the SQL does",
    "bindingCode": "Dart FutureBuilder snippet",
    "nextStep": "what the user should do next"
  }
═══════════════════════════════════════════════════════════`;
};

// Helper for SQL type mapping
const mapType = (t) => {
  const map = { text: 'TEXT', numeric: 'NUMERIC', boolean: 'BOOLEAN', uuid: 'UUID', timestamp: 'TIMESTAMPTZ' };
  return map[t] || 'TEXT';
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 10: REPAIR CONTEXT (NEW v2.0)
// Specialized for the 1-Click Auto-Repair Engine.
// ─────────────────────────────────────────────────────────────────────────────

export const compileRepairContext = (schema, errorLogs, task = 'Fix the build error') => {
  const base = compileFlutterContext(schema, task, {
    includeThemes: false,
    includePatterns: false,
    verbosity: 'compact',
    repairMode: true,
  });

  const errorBlock = `
═══════════════════════════════════════════════════════════
AUTO-REPAIR ENGINE — ANALYZE AND PATCH
═══════════════════════════════════════════════════════════

BUILD ERRORS:
\`\`\`
${errorLogs.slice(0, 3000)}
\`\`\`

REPAIR PROTOCOL:
  1. Identify ROOT CAUSE (not just the symptom line)
  2. Determine if it's fixable by:
     (a) A schema node prop change (preferred — no code edit needed)
     (b) A Dart code patch (for generator logic issues)
  3. Output a JSON patch in this EXACT format:
  {
    "rootCause": "One-sentence diagnosis",
    "fixType": "schema_patch" | "code_patch" | "import_fix" | "type_cast",
    "severity": "critical" | "warning" | "info",
    "schemaPatch": {
      "nodeId": "the node id to fix",
      "propChanges": { "prop": "newValue" }
    },
    "codePatch": "exact Dart code replacement if fixType is code_patch",
    "terminalMessage": "User-friendly one-liner for the build log",
    "confidence": 0.0-1.0
  }

COMMON ROOT CAUSES FOR THIS SCHEMA:
  - Unbounded Column inside ListView → add shrinkWrap: true (L-2)
  - Text in Row without Expanded → wrap with Expanded() (L-3)
  - Missing width/height on Image → add width: double.infinity (L-4)
  - Using ! on nullable → replace with ?. and ?? (Rule N-1)
  - Missing 'mounted' check after await → add if (!mounted) return (L-8)

SCHEMA QUICK REFERENCE:
  Pages: ${schema.pages?.map((p) => p.id).join(', ')}
  State: ${(schema.appState || []).map((s) => `${s.key}(${s.type})`).join(', ') || 'none'}
  Tables: ${(schema.appConfig?.dbTables || []).map((t) => t.name).join(', ') || 'none'}
═══════════════════════════════════════════════════════════`;

  return base + errorBlock;
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 11: THEME CONTEXT HELPER
// ─────────────────────────────────────────────────────────────────────────────

export const compileThemeContext = (schema, task) => {
  return `You are an AppForge UI/UX design engineer.
TASK: ${task}
${buildDynamicThemeBlock(schema)}
OUTPUT: A complete ThemeData object or styled widget. Use ONLY the token constants defined above.`;
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 12: DEPENDENCY HELPER
// ─────────────────────────────────────────────────────────────────────────────

export const getDependencies = (schema) => {
  const scan = scanSchema(schema);
  const deps = { http: '^1.2.0', provider: '^6.1.2', flutter_dotenv: '^5.1.0' };
  if (scan.hasSupabase) deps['supabase_flutter'] = '^2.3.4';
  if (scan.hasFirebase) { deps['firebase_core'] = '^2.27.0'; deps['firebase_auth'] = '^4.17.0'; deps['cloud_firestore'] = '^4.15.0'; }
  if (scan.usesMap) deps['google_maps_flutter'] = '^2.6.1';
  if (scan.usesWebView) deps['webview_flutter'] = '^4.7.0';
  if (scan.usesVideo) deps['video_player'] = '^2.8.3';

  return `dependencies:
  flutter:
    sdk: flutter
${Object.entries(deps).map(([k, v]) => `  ${k}: ${v}`).join('\n')}`;
};

export default {
  compileFlutterContext,
  compileRepairContext,
  compileBackendContext: compileBackendWizardContext,
  compileThemeContext,
  getDependencies,
  buildDynamicThemeBlock,
  WIDGET_KNOWLEDGE,
  BACKEND_KNOWLEDGE,
  STORE_THEMES,
  STRUCTURAL_LAYOUT_RULES,
};