import JSZip from 'jszip';

export async function POST(request) {
  try {
    const body = await request.json();
    const { dartCode, appName = "appforge_export" } = body;

    if (!dartCode) {
      return new Response(JSON.stringify({ error: "No Dart code provided" }), { status: 400 });
    }

    const zip = new JSZip();

    // 1. Create the lib directory and add our generated main.dart
    const libFolder = zip.folder("lib");
    libFolder.file("main.dart", dartCode);

    // 2. Create the standard pubspec.yaml file required for every Flutter app
    const pubspecConfig = `name: ${appName.toLowerCase().replace(/\s+/g, '_')}
description: A new Flutter project generated by AppForge.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
`;
    zip.file("pubspec.yaml", pubspecConfig);

    // 3. Create standard boilerplate files (Optional but good for completeness)
    zip.file("README.md", "# AppForge Export\n\nThis is a production-ready Flutter app generated by AppForge.\n\n## Getting Started\n1. Run `flutter pub get`\n2. Run `flutter run`");
    
    // 4. Generate the ZIP file as a buffer
    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    // 5. Send it back to the frontend as a downloadable file
    return new Response(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${appName.toLowerCase().replace(/\s+/g, '_')}.zip"`,
      },
    });

  } catch (error) {
    console.error("Export Error:", error);
    return new Response(JSON.stringify({ error: "Failed to generate zip" }), { status: 500 });
  }
}